### ISSUE TITLE
enhancement: Instance suggestion page

### ISSUE THREAD

**Issue by latrani** [tootsuite/joinmastodon#5]
A page that asks a few questions from users and suggests an instance pulled from an opt-in database.

Mockup is available here:

https://latrani.github.io/joinmastodon/

This will need a backend and a way for instance admins to add themselves (providing the language info, description blurb, etc)

Some design doc stuff is here: https://public.etherpad-mozilla.org/p/Z3rHK08QsZ

**Comment by haniawni** [comment]
Considering the wide variety in instance cultures, and the increasingly immense number of instances, it seems to be that the dominant factors for where a new user should go would, in the current design, only be captured through the text field on the instance description.

Instead asking about social norms or the purpose of the instance in a way that provides easy filtering to match ppl with instances they actually will enjoy being at seems to me like it'd make the site vastly more useful.

This could be done with:

1) asking a bunch of questions, OkCupid style, of the user about extent of agreement with statements ex "I value being able to disengage from politics whenever I get overwhelmed" or "I'd like to meet other furries/scalies/etc". I worry the number of questions would soon become far too big this way, though, and every instance would need to constantly be inputting data on how they relate to new dimensions that are most likely irrelevant (ie. Is candy.land a good place to discuss BDSM techniques?)
2) alternatively, instances could "tag" themselves with short tags- "safe space", "activism", "personal branding", "witches", "japanese only", "NSFW"- which the instance picker can then use in a search style to help guide user toward suitable instances.

I strongly prefer 2, because this data of tags can then also be used by instances when determining rules for inter-instance toot translation- an admin/user could establish a rule saying "all toots from an instance tagged "NSFW" should be auto-CW'd and auto-NSFW'd" or "I want to silence all instances that tag themselves with 'personal branding'"

**Comment by latrani** [comment]
The tags idea is a really good one, though a concern I have there is seeding it; if we only have on the order of hundreds of instance entries in the DB, all self-report, we might not get enough conversion on tags for that to be better than noise.

Is there a way we can think of to try to pre-seed such a database, possibly based on the admin's self-reported "description blurb" stuff?

That might also help address something that I think alluded to in your last comment; some of this seems like it wants to be (loosely) structured, especially when it comes to defining stuff like instance social norms.
