### ISSUE TITLE
enhancement: "Notable users" info

### ISSUE THREAD

**Issue by latrani** [tootsuite/joinmastodon#7]
As a way to show Mastodon's reach, possibly as part of the feature list (#4), there could be a list of orgs using Mastodon, e.g. Pixiv, Numerama, etc.

**Comment by haniawni** [comment]
I'm personally very wary of highlighting externally-powerful entities out of all the members of the Fediverse; though I'm not sure how well I'm doing at expressing my specific concern.

What I mean is- rather than "_here are famous groups that are using mastodon_", what about a "_community highlight_" sort of thing? This reframing lets us point a spotlight toward particularly unique, unusual, artistic, or interesting instances or users- like Oulipo.social, emphemeral.glitch.social, or the like- rather than highlighting only what organizations IRL are using it. Note that a community highlight approach still leaves room for highlighting Pixiv, Numenara, or the like; but taking this framing highlights the potential of GnuS/Masto for facilitating **communities with shared interests** rather than highlighting **the organization itself**. This framing would also naturally suggest potential crowdsourcing of Communities to highlight, in order to avoid the "Verified:tm:" connotations of having Mastodon-the-project choosing groups/users to designate; I personally am exceedingly disinterested in replicating decisions like Verification:tm: that Birdsite made which drive toxic social power imbalances.

My rationale for this suggestion is that while the "Famous Orgs" framing advocates a "Mastodon as tool, like Slack" narrative, the "Community Spotlight" framing advocates a "Fediverse as diverse array of a multitude of different communities, all composed into larger meta-communities" narrative, which prioritizes the **social, cultural, configurable, and liberating** potential of the technology. It is these social, cultural, and liberating aspects that, in my opinion, underlie the true potential of the FOSS and federated nature of this project.

**Comment by mjankowski** [comment]
It'd be interesting to aggregate both popularity things like user count, but also things like "most popular hashtags in last month" or something, to help people find instances.

I also like the idea of an aggregated and emergent highlighting of instances, rather than a top down curated one.

**Comment by alexgleason** [comment]
I like the idea of using stats to show information, since it's curated by software and determined by the community. This lets power be distributed.

But I'm wary of highlighting people by their follower count due to the potentially harmful psychology behind this. I'd at least rather the follower count be obfuscated in some way or maybe not display.

Ideally a goal of community controlled social networks like Mastodon would be to improve user's mental and emotional health, while birdsite is about making users addicted for profit. Follower counts can make people feel inadequate or holier than thou depending on the direction. I'd rather avoid that to the greatest degree possible here.

**Comment by alexgleason** [comment]
@haniawni I very much agree with you, but how can we execute that? The content needs to be curated by something.

**Comment by Irick** [comment]
Why not use both?
It should be simple to provide a toot viewer that strips usernames and follow counts. We could have a crawler that looks for instances with bursts of activity (high rate of new follows, new users, boosted toots etc),  picks out ten such instances and provides anonymised example toots for whoever is in charge of promoting mastodon to choose from. We could also have it explicitly select a certain quota of low, medium and high user count instances (maybe 2 high, 3 medium, 5 low?) if we want to. Maybe throw in some hand selected choices from other members of the workgroup if we are unhappy with a fully data driven approach.

This way we don't risk an autonomous system getting heavily gamed but we don't have to resort of too much investigative footwork to get candidates.

**Comment by latrani** [comment]
Just to add some context, this was captured off of some @Gargron thoughts from the Discord, it's not a specific ask, just one of several brainstorm ideas that I thought should get preserved for the sake fo discussion. :) I'm not a project-manager here, just an archivist.

**Comment by fermuch** [comment]
It's always a good sign to see some brands you already know using the same software you're about to use. If I know about Pixiv, I'd be more likely interested in Mastodon if I want to give it a try.

I'm not against about doing some automatic collection of stats for display, but we have to be very wary of what is included. It might be the first door for someone wanting to join the network, and having a trending hashtag like #ISIS on the front page because some instances are using it as a joke, might not be ideal.
